# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

# Stage 1
# Build Docker Image
# Publish the K8S Files

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '6cf325ae-0683-4cf2-9dfb-0e2e178e6b6e'
        definition: '2'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'KubeC'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
        containers: 'uday4r4nds/microserviceone:0.0.5.RELEASE'
# Stage 2
# Download the K8S Files
# Deploy to K8S Cluster with Docker Image