apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-07-04T09:03:22Z"
    generation: 1
    labels:
      app: microserviceone
    name: microserviceone
    namespace: default
    resourceVersion: "27490"
    uid: e5474414-59f5-42ea-827d-69ef8b769907
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: microserviceone
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: microserviceone
      spec:
        containers:
        - image: uday4r4nds/microserviceone
          imagePullPolicy: IfNotPresent
          name: microserviceone
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""

---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-07-04T09:03:41Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: microserviceone
    name: microserviceone
    namespace: default
    resourceVersion: "27590"
    uid: 7c411bc4-e2c8-4a27-abc3-5adaa7164584
  spec:
    ports:
    - nodePort: 31252
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: microserviceone
    sessionAffinity: None
    type: LoadBalancer
  
kind: List
metadata:
  resourceVersion: ""